### ISSUE TITLE
K8s generated version of the Overview dashboard should reference the dependency on grafana-polystat-panel plugin

### ISSUE THREAD

**Issue by jakerobb** [datastax/metric-collector-for-apache-cassandra#25]
`dashboards/k8s-build/generated/grafana/overview.dashboard.yaml` looks like this (I've omitted the JSON chunk for brevity):

```
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  labels:
    app: grafana
  name: overview
spec:
  json: "{ ... }"
  name: overview.json
  url: https://raw.githubusercontent.com/datastax/metric-collector-for-apache-cassandra/master/dashboards/grafana/generated-dashboards/overview.json
```
But when you load the resulting dashboard, the polystat panel contains an error stating that you're missing a plugin. To resolve, the generated YAML should look like this:
```
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  labels:
    app: grafana
  name: overview
spec:
  json: "{ ... }"
  name: overview.json
  url: https://raw.githubusercontent.com/datastax/metric-collector-for-apache-cassandra/master/dashboards/grafana/generated-dashboards/overview.json
  plugins:
    - name: grafana-polystat-panel
      version: 1.2.2
```
