### ISSUE TITLE
Example filters and alerts

### ISSUE THREAD

**Issue by StevenLacerda** [datastax/metric-collector-for-apache-cassandra#47]
We should have more examples of alerts and filters. Here's a filter that helped the performance go from about 20s to under 1s whittling the metrics down from 115k to 3.5k:

```
filtering_rules:
 - policy: deny
   pattern: system_auth
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.(keyspace|table).*(system_(?!auth)|system\.(?!(paxos|batches))|ds_|solr_admin|system$).*
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.client_request\..*\.cas_(read|write)
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.keyspace.*
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.table\.cas.*
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.table\.percent_repaired.*
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.table\.row_cache.*
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.table\.view.*
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.table\.bytes_anticompacted.*
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.table\.bytes_mutated_anticompaction.*
   scope: global

 - policy: deny
   pattern: org\.apache\.cassandra\.metrics\.table\.memtable_switch_count.*
   scope: global

```

I don't have any alert examples, but we should create some.
