### ISSUE TITLE
Metrics are lost after 5 minutes

### ISSUE THREAD

**Issue by jpicara** [datastax/metric-collector-for-apache-cassandra#73]
Hi,
I would like to ask for support for the following issue we are suffering in which we are loosing the metrics collector in our Prometheus instance.

**Prometheus scrapping.**
```
- job_name: "mcac"
  scrape_interval: 30s
  scrape_timeout:  20s
  honor_labels: true
  metrics_path: /metrics
  consul_sd_configs:
  - server: consul.service.consul:8500
    services:
      - 'cassandra'
  relabel_configs:
  - source_labels: [__address__]
    action: replace
    regex: ([^:]+):.*
    replacement: $1:9103
    target_label: __address__
  metric_relabel_configs:
   #drop metrics we can calculate from prometheus directly
   - source_labels: [__name__]
     regex: .*rate_(mean|1m|5m|15m)
     action: drop
     #save the original name for all metrics
   - source_labels: [__name__]
     regex: (collectd_mcac_.+)
     target_label: prom_name
     replacement: ${1}
```

Note: We know that more relabel configs are needed but just omitted to test this out.
In our case we cannot define a static IPs for the cassandra nodes as instances can take any IPs from a range using consul service discovery to create the enpdoints needed.

Job is properly created and pointed to the right cassandra instances. However, firstly we need to restart the cassandra node to start getting the metrics because of the following log output error
`"Error on ingesting samples that are too old or are too far into the future" num_dropped=198729`
After doing it, metrics start coming to Prometheus but after exactly 5 minutes, all of them went away.

**collectd.log**
`cassandra@cluster-datacenter1-default-sts-0:/var/log/cassandra$ tail -f cassandra-collectd.log
[2022-07-01 07:30:37] plugin_load: plugin "uptime" successfully loaded.
[2022-07-01 07:30:37] plugin_load: plugin "processes" successfully loaded.
[2022-07-01 07:30:37] plugin_load: plugin "tcpconns" successfully loaded.
[2022-07-01 07:30:37] plugin_load: plugin "match_regex" successfully loaded.
[2022-07-01 07:30:37] plugin_load: plugin "target_set" successfully loaded.
[2022-07-01 07:30:37] plugin_load: plugin "target_replace" successfully loaded.
[2022-07-01 07:30:37] unixsock plugin: Successfully deleted socket file "/tmp/ds-8466130650012646173.sock".
[2022-07-01 07:30:37] cpufreq plugin: Found 0 CPUs
[2022-07-01 07:30:37] Initialization complete, entering read-loop.
[2022-07-01 07:30:38] tcpconns plugin: Reading from netlink succeeded. Will use the netlink method from now on.
[2022-07-01 07:35:53] plugin_dispatch_values: Low water mark reached. Dropping 100% of metrics.
[2022-07-01 07:35:54] plugin_dispatch_values: Low water mark reached. Dropping 100% of metrics.
[2022-07-01 07:35:57] plugin_dispatch_values: Low water mark reached. Dropping 100% of metrics.
[2022-07-01 07:36:07] plugin_dispatch_values: Low water mark reached. Dropping 100% of metrics.
[2022-07-01 07:36:17] plugin_dispatch_values: Low water mark reached. Dropping 100% of metrics.
[2022-07-01 07:36:20] plugin_dispatch_values: Low water mark reached. Dropping 100% of metrics.`

![image](https://user-images.githubusercontent.com/6992066/176847754-421b6989-86ee-4103-9663-c2899ba642b2.png)

Could some help up?
Thanks in advance
